apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sample-app-db
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secretTemplates:
        - name: sample-app-db
          stringData:
            DB_USER: ENC[AES256_GCM,data:z73H,iv:3ADQWjXK9vfGhFDtb/yuYn/h5s0TaTVrTaBNgY2H/tg=,tag:TlGY+C8WcsLE0Fu9MIlCBQ==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:Pw1116pm+TA7A1a4YjfslTD7Ah3u/q38rB2TCOUrLA==,iv:gy9YTZHR9lGQ5GyBHucy715FJa3GrDeFlrxjzdKtOB4=,tag:Vx5wnuZwuPZBqMtOd7gHkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTHhGOERZZUl6VVNMUkJp
            OWI0bEt1bGNmVjA3cXBQazZMcGJGbXNWOVZBClR0U0cweWI1L2pYKzBrMXhER0Jv
            ZmhqbjNYdVhUT3ZjTkQrZlZiV3g2ZVkKLS0tIDdzdmZmdEk3QkhTYTh0ZCtMaVJB
            c1N0azJwVzFvYlVtRE1tcW0rNVFXYkUKSoT3cSs/IW0r/z4FD3YF730ydMHhV0cK
            RbkiqfOliP15rPevT0DQvS5TOW4DFPyWcXYL6FYi2wone/9RHHTcyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18fd0sxteh5ddq0xhmdew42qxlzx7ylmuchsqs0xvdd0twazh745sxh65gy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS2NyWFg0bFFJQ3REZXJm
            Rk5ubVVLZGxHb010VWIyZGJKMzNxWGkwTlZnCnh3c0szcmlPbVZ4OEpsSXZOS2JV
            M2NWd1hwMjk0em5Cbnc0V0R0M0hRSW8KLS0tIFYvZFdjRWhvZmVQRWJ4MmxpYUdL
            RVZQc2t5aXFCcFV6M2xqMlRJeHJFaUEKFikIE5hMdgK7NWwdRrKnAlXUqeeD1+nX
            /IZNsi+Aq3eN4Bt6JzzpWMv/Vg39XEJr9hfs/ee/PLfB4BmpsV3xwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e2yjf2v46pkh46ud4ajnpy34cle22glnq36hzmmgphszu3r78ukq3l2s48
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T19:42:57Z"
    mac: ENC[AES256_GCM,data:nv9jZsu8/zheXkTJ552y09pYDs3v+v6cQkoDIKzEoNbadJIeucL+WSZZcKnzhZ9aKa3lrjn7h+J2rzXmptza3WgjB/7Gdg261Ys0go+fZ2M/Yjp8/qArBUzKnbFIofeFOJfMAhidSrTLOs46GDUsrRRdOUne6v7SaCiW7QQIZso=,iv:76i43gxZ0VejHvaYZofTzJCWDjmp9zU9srM1cxEotOc=,tag:jAzWmtECZxJd1DqmeLd52Q==,type:str]
    version: 3.13.3
