apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sample-app-db
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secretTemplates:
        - name: sample-app-db
          stringData:
            DB_USER: ENC[AES256_GCM,data:Xqnq,iv:O72VFqn5TyMFiqtVSLg9t5xdydM12jG6n1XBeAb1ydI=,tag:31uyViPTieYg/F22+juQFA==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:va8TAL0GmsCphK2MGBnjvnYx6LZdWyxrj0XifuMADA==,iv:LZE8feoMmkwmO/XH7ZFdQv1PKsGAJk150iEkyhgKzBk=,tag:X/uQJxOuAAwzFRv5JWxW5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ2ZFdUdkOEtoTmFXQUh0
            b1RiWTBvL0llT1NtNVIzdXFpZld3VnJsUm5jCjExY2dTMnN5MEcyRGdNL0FJbjZq
            MTYzOVd3MmQ4UUhzcG95NTJ1d0VJTmsKLS0tIERVaU9Cb2JEaG9qOW9iMU9Ha1Rq
            N0wzMzFJRWgzL1RvT0V1TDQwOThadk0Kgk8DykzH8R6mQeZ9J7ujhsnE1suNPyzS
            Bf0m58uAoF78KF9yIrnp/chgysmKhZ7kYP5C7Da7DKsrDjlmWIqpFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18fd0sxteh5ddq0xhmdew42qxlzx7ylmuchsqs0xvdd0twazh745sxh65gy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFFuZVVoTFJjZ1Zvbkp6
            MzVuYlo1RmRPbGhrdzFQMXlrN0NPdHFUZVdjCjFXOTFVSFpic2tFeTBKY2hVMnlB
            NllVZ1JqdXRxTUFEQnBKc2Q3UHhiTDgKLS0tIGtrZVZ6MVBqWkdGS0J2YWtKaUcx
            ZlZFcmN5MHdlUnZpaTJDRTlwaHFMQW8KVInXcB32hKR37krK8rJl4HUV2Vbd7vxz
            2V6PigwKJCwyblue2wp/4BxIpdoL/7MEJ2YQ1gJJzRQiF8DpJNlGTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10hrlhwa77c8kkcdpt0wucep7xyn30le68kzsak5uezzp9m8kpqxqt9w6s2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T19:42:57Z"
    mac: ENC[AES256_GCM,data:yaategXjjtedhU91Ho4mEIVIdGGaBbyuQUSJ+nSD4t4wS/i3ExNhHriUD8MRtIuIT1fgEWeoSw3z/Rs2ef3E1MSODzDkunqASszYGk2K3lPwYxyeqPfEphJeqFNFHuj+evZrDtoT84kHXBnN0fvzGFThikDHgbH+ofYlphEro9I=,iv:3Ub7Xe4aO++llSwqA6D/FfLRSsef22e5Qbqaw2cliDg=,tag:0CwOK2jJg8zPjc0gWYkU8A==,type:str]
    version: 3.13.3
