apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-notifications-secret
spec:
    secretTemplates:
        - name: argocd-notifications-secret
          stringData:
            slack-webhook-url: ENC[AES256_GCM,data:hTYiJyXEXFYpCa2/yvj0wDijj3ca4sO7KZ6cGrltkNN8+wObNOQCH+kGX9AFAnaGgMNBEeSUbzmv+5DoN50WPrXvh3fGVBykBg1azxb1xFWC,iv:BMv0OcHhk/otwFBpzXL0WSRt63Nbj42bq0FTxYU8xV0=,tag:6d/Imn/D3RRB8Fp3NBGmsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTnFNTWhWOWxBL1NoNkM0
            ZUxEWVovaVltdTV1Tm5BczI2ZDZ6U2tIeVhJClNLWW5PUndKNmp5dmZhZG83YTA1
            eng3dnFZbUZiT0NhUURTV3JadnpsUU0KLS0tIGNBMkN3VGgyZHQ2Q3I2RkFSZWtU
            aGZxRWFTUWhLV2MzcnlPcjdob0svcXcKcC/NRIfKT4BgfBYPxVmMSdqn0zxWinuj
            zDMyhzSSnh8rg5iu87Wb6dDRE5tTYsBGdi2jaf0mtHJemol6jZjm8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18fd0sxteh5ddq0xhmdew42qxlzx7ylmuchsqs0xvdd0twazh745sxh65gy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYazV2ZlZROVREZkpXbXIx
            Kzd3cE9yMFI4K1dham1aWUtOTExRTHloNlZzCjZSUHdxSklVR3VOa2VKcTNLdCtB
            dy96OGZobDVFaU1HaXZDT01jakFFOEEKLS0tIGdqQnlra3dCcXEwWXV3a3hEOUR4
            Ty9vaUVSa3NyUUVkMEdGZ0FFN1hKNTgKJGlpVsunF2bvf4ikWOCE6UrUlCt6kcXc
            e8CgktdxCCZY4QhSfK7zlBMR83ou1Rk8ruxlbJC0VOKs/uTuIkOLqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xh9ac3qd8dt670p3dzgxwjgw2fx895ge0zeehc3ls000t4ewcp7scmssha
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T11:42:48Z"
    mac: ENC[AES256_GCM,data:eDP3mX3z/lSqnN15QjD5EPP5zfjUquoeqiBCTqVAv5SAKn2LkgfW3BtlZTxBdJovaNGnhcNXts8qF7LTcC9rmRJK+9LuWsgJFzicBSTXyJaVimZEXlaR+SxZcVnuTSsGV8/XcyFQsNLPm7Tr61YjLmJH2k+X7ujh4IA/klwKyQo=,iv:SamX5O33mzIWMNXJkAEVjtxsebGTTXbE3h7CTnt1P5Q=,tag:9u4Kfo0MP6TgA82rjRjVmA==,type:str]
    version: 3.13.3
