apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-slack
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secretTemplates:
        - name: alertmanager-slack
          stringData:
            url: ENC[AES256_GCM,data:fHpFCsPlJkzitYt7F+hxo+rcF/Wlx/xuMV5Q9UNPkoleaCPa4q1WKWLw0zQYeeaAZ0n9KG1/26RWDKJ6Y0lC0XI7LXHnWL2Zn+KkH2PYejZA,iv:1RHhWxg8Slbbpm2jQxinHZk+7ZTMtqETL3ClFkSArlA=,tag:N0KJDjTdUVP1MSrvrOFXMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeCsxQlB0U1lVcXc0RzBR
            ZDJOb0NXWWlicVQzUUVTLytaZ1dFUHFnMGk4Ckp6REc0Ulh3WmdBSGJuU0VXR2pl
            eExEdDdCTC9PcldhNC80T3RlY2tMKzgKLS0tIGgyZ0tiM20wM0dhWW9wL296N1k0
            Y2VFaml0ZjVhZ3NHWDNETHBZR3ZlMjgK4Nzub3bOCJmBOZfsqBu6j/K9XCYorFB+
            DTCO9mvwngu9qtPpFLEkRuCMIlI7GTFTm17lVC0b5YuAijH/OjxUAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18fd0sxteh5ddq0xhmdew42qxlzx7ylmuchsqs0xvdd0twazh745sxh65gy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVGRPbUJpQ0dxeG9xQTlV
            V29hNHdEMTRRQkVKZUk3c0libU0zNk1abm1rCnJiSGZjczN6WjJLbjVUMDBDdVBZ
            TVZMeE1MZlZvTldSczA1dGM2bmNWTWcKLS0tIFVtUDl0UmJZYzNlNEN1TzZjeDk5
            RUFHanFSUStxcTFHMmNsQzRWRzhVQlEKbhyVC9bH6NUyqWpBLZleAk2oUZgCkru2
            /cMn2vEFhpDhYgyHs3MeO8iYmBzWKHi+I/nZlPIjCuXUymyVW60/Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e2yjf2v46pkh46ud4ajnpy34cle22glnq36hzmmgphszu3r78ukq3l2s48
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T09:50:34Z"
    mac: ENC[AES256_GCM,data:YkZcZ3k5dhQzz72GvOzqx66JEcEr3MsIbnvyGyOtaww53ItDM3MhZNzvkjh1/JVTI+nminLSabPRsc5v+UIPjJ2DqmzXOxMyCX1NcP39KFsVvumBQd/Jk+BJ3yMXpJu4ggXcQ6KVlJD5CX3n8M6GCxA98kyLeXeawXzwvwf6000=,iv:77KZw1El6+reGDbq4+cdk9zX+w02xgLvaxPlY9tlYpc=,tag:TDioufkDW9oQJRBJkU0qBw==,type:str]
    version: 3.13.3
