apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-slack
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secretTemplates:
        - name: alertmanager-slack
          stringData:
            url: ENC[AES256_GCM,data:Fdv2jOfOxv5KG8NxJfYxXKSA3KUTDQnAxBYzME1I/G/yBsbBnwB0GTCCQlpuiaSn6cPyiEYdb7deIBe0qtMkI88weKn1m3qBD3VvfDnNPyvk,iv:kfhu2m0KiFhzr54SBIBNObjSirUWTKx4v9u4l6m46r0=,tag:sPSsncn/Xba3vIu226xWVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQTRPTXNLajIxL1k1bjJM
            MThIZTU1cHNxOUlvdTl1VTB6bnBYendCL0ZJCjF3REdjYjNjUDZWeDlkZGZSTllB
            UHNsUFVldXRldWNZdUw2ZVcrSkdROWsKLS0tIE9obWpYODdTSkwwREQ1bmJYYm44
            NzRYSWdDZGVBU2F6cm9WekM5WlNIVk0Kkzw8Q9ZkJqere5Cszr5faEcNOEc57k2e
            avgyI3miDxQRre+l6pPTdyz3ykwgLIyFNxi8eQ3OCrpFYCjn1w2UGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18fd0sxteh5ddq0xhmdew42qxlzx7ylmuchsqs0xvdd0twazh745sxh65gy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzYwZE12eE40dHU3N2tV
            QkVxaW03ZUx5c01uQWpRWkdZQnhqN1lnNm04CmV4V09HaW5KazBzWEh6WjR3V0lZ
            UmM4bWh0K1c1eXJVWE41a3J3TjNiT00KLS0tIGJHd0sxUHNnZGN6eXR0amozNzZZ
            WWsvNXpyZXlVNmtLWkhUN3hCWEExWlEKFyP+qY+NOhdlxC8gbJOvXqmY/+ySGOmp
            Z8pUqfXwIx97qmxDI1wlu/YYL/aT8GW3UY3OuOCSJLQ6Wa7ZK9AM5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10hrlhwa77c8kkcdpt0wucep7xyn30le68kzsak5uezzp9m8kpqxqt9w6s2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T09:50:34Z"
    mac: ENC[AES256_GCM,data:gpDIpN+353sNanqiuZ9EF9zX5NIey8PXFn7tGKTJ93OEhvsfrmCv1OGiQwuz9ILFJ2zksuYjU0g+INB6GxLrc/E5e1V75Ok4ECnkDuEkcaWYjPchbnqGwMIRy1WnMS42NwEOexbC6sjID6vQdwPrlkgpLYQryuqg4y6jDwBzyl8=,iv:3ouNp1G4Gp38rJ4uJX1n4Tg7Mbm65WN+araWTFxca10=,tag:NpL9c0D4ZOd6MdwUxbv5vw==,type:str]
    version: 3.13.3
